// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLshX_xqqPid3bHqX7kOkbpHUGX9XyGBU',
    appId: '1:970429460081:web:90caa725d9abac5a14b5d0',
    messagingSenderId: '970429460081',
    projectId: 'crud-firebase-f8db5',
    authDomain: 'crud-firebase-f8db5.firebaseapp.com',
    storageBucket: 'crud-firebase-f8db5.appspot.com',
    measurementId: 'G-GE7X9CJNQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnihsKk5zUrgFkTTk4rRVQb3PfY-De2AM',
    appId: '1:970429460081:android:f4a1babc2416f04914b5d0',
    messagingSenderId: '970429460081',
    projectId: 'crud-firebase-f8db5',
    storageBucket: 'crud-firebase-f8db5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mLJldGkXtS8r_ZYtuUPfCUZrpK_mEJo',
    appId: '1:970429460081:ios:ec621a76824f6ac714b5d0',
    messagingSenderId: '970429460081',
    projectId: 'crud-firebase-f8db5',
    storageBucket: 'crud-firebase-f8db5.appspot.com',
    iosClientId: '970429460081-rrp65lbvd7dg6hduvh2oq7rcfq7k922r.apps.googleusercontent.com',
    iosBundleId: 'com.example.signIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mLJldGkXtS8r_ZYtuUPfCUZrpK_mEJo',
    appId: '1:970429460081:ios:ec621a76824f6ac714b5d0',
    messagingSenderId: '970429460081',
    projectId: 'crud-firebase-f8db5',
    storageBucket: 'crud-firebase-f8db5.appspot.com',
    iosClientId: '970429460081-rrp65lbvd7dg6hduvh2oq7rcfq7k922r.apps.googleusercontent.com',
    iosBundleId: 'com.example.signIn',
  );
}
